version: '3.8'

services:
  web:
    build: .
    ports:
      - "80:80"
    environment:
      - APACHE_RUN_USER=www-data
      - APACHE_RUN_GROUP=www-data
    volumes:
      - ./uploads:/var/www/html/uploads
      - ./data:/var/www/html/data
    restart: unless-stopped
